// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-template/internal/model"
	"go-template/internal/pkg/config"
	"go-template/internal/pkg/database"
	"go-template/internal/pkg/logger"
)

// Injectors from wire.go:

// wireApp init
func wireApp() (func() error, func(), error) {
	allModel := model.NewModel()
	configConfig, err := config.InitConfig()
	if err != nil {
		return nil, nil, err
	}
	zapLogger, cleanup, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := database.NewDB(configConfig, zapLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v := newApp(allModel, db)
	return v, func() {
		cleanup2()
		cleanup()
	}, nil
}
