// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-template/api/engine"
	"go-template/api/handle"
	"go-template/api/routers/v1"
	"go-template/internal/biz"
	"go-template/internal/data"
	"go-template/internal/global"
	"go-template/internal/pkg/auth"
	"go-template/internal/pkg/config"
	"go-template/internal/pkg/database"
	"go-template/internal/pkg/db"
	"go-template/internal/pkg/logger"
	"go-template/internal/pkg/permissions"
)

// Injectors from wire.go:

// wireApp init
func wireApp() (func() error, func(), error) {
	configConfig, err := config.InitConfig()
	if err != nil {
		return nil, nil, err
	}
	zapLogger, cleanup, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	baseHandle := &handle.BaseHandle{
		Log: zapLogger,
	}
	gormDB, cleanup2, err := database.NewDB(configConfig, zapLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	idb := db.NewDB(gormDB)
	client, cleanup3, err := database.NewRedis(configConfig, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseRepo := data.NewBaseRepo(idb, client)
	userRepo := data.NewUserRepo(baseRepo)
	ijwt := auth.NewJWT(configConfig)
	userBiz := &biz.UserBiz{
		Log:      zapLogger,
		UserRepo: userRepo,
		Jwt:      ijwt,
	}
	enforcer, err := permissions.NewCasbinEnforcer(gormDB)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userHandle := &handle.UserHandle{
		BaseHandle:    baseHandle,
		UserBiz:       userBiz,
		CasbinService: enforcer,
	}
	userRouter := &v1.UserRouter{
		UserHandle: userHandle,
	}
	routersV1 := engine.NewRoutersV1(userRouter)
	iAuth := auth.NewAuth(configConfig)
	globalGlobal := global.InitGlobal(iAuth)
	engineBase := engine.NewEngineBase(routersV1, configConfig, zapLogger, globalGlobal)
	engineAuth := &engine.EngineAuth{
		EngineBase: engineBase,
		Jwt:        ijwt,
	}
	v, err := newApp(engineAuth)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return v, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
