// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/biz/user.go
//
// Generated by this command:
//
//	mockgen -source=./internal/biz/user.go -destination=./internal/biz/mock_user.go -package=biz
//

// Package biz is a generated GoMock package.
package biz

import (
	context "context"
	domain "go-template/internal/domain"
	model "go-template/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserRepo is a mock of IUserRepo interface.
type MockIUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepoMockRecorder
	isgomock struct{}
}

// MockIUserRepoMockRecorder is the mock recorder for MockIUserRepo.
type MockIUserRepoMockRecorder struct {
	mock *MockIUserRepo
}

// NewMockIUserRepo creates a new mock instance.
func NewMockIUserRepo(ctrl *gomock.Controller) *MockIUserRepo {
	mock := &MockIUserRepo{ctrl: ctrl}
	mock.recorder = &MockIUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepo) EXPECT() *MockIUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUserRepo) Create(ctx context.Context, cp *model.SysUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIUserRepoMockRecorder) Create(ctx, cp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserRepo)(nil).Create), ctx, cp)
}

// Delete mocks base method.
func (m *MockIUserRepo) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIUserRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUserRepo)(nil).Delete), ctx, id)
}

// GetByUserName mocks base method.
func (m *MockIUserRepo) GetByUserName(ctx context.Context, userName string) (*model.SysUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserName", ctx, userName)
	ret0, _ := ret[0].(*model.SysUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserName indicates an expected call of GetByUserName.
func (mr *MockIUserRepoMockRecorder) GetByUserName(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserName", reflect.TypeOf((*MockIUserRepo)(nil).GetByUserName), ctx, userName)
}

// PageInfo mocks base method.
func (m *MockIUserRepo) PageInfo(ctx context.Context, req *domain.UserListRequest) ([]*model.SysUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PageInfo", ctx, req)
	ret0, _ := ret[0].([]*model.SysUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PageInfo indicates an expected call of PageInfo.
func (mr *MockIUserRepoMockRecorder) PageInfo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PageInfo", reflect.TypeOf((*MockIUserRepo)(nil).PageInfo), ctx, req)
}

// Retrieve mocks base method.
func (m *MockIUserRepo) Retrieve(ctx context.Context, id uint64) (*model.SysUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", ctx, id)
	ret0, _ := ret[0].(*model.SysUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockIUserRepoMockRecorder) Retrieve(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockIUserRepo)(nil).Retrieve), ctx, id)
}

// Update mocks base method.
func (m *MockIUserRepo) Update(ctx context.Context, cp *model.SysUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIUserRepoMockRecorder) Update(ctx, cp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUserRepo)(nil).Update), ctx, cp)
}
